# Site settings
author: Savannah Younts
title: Sav Younts 
header-img: img/home-bg.png
email: savyounts@gmail.com
copyright_name: Savannah Younts
description: > # this means to ignore newlines until "baseurl:"
  Web Developer. World Traveler. Climber. Designer. Do-er. ✌️
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  savyounts

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
